"""
Log Template Miner — Drain3 pattern extraction from paper_trading.log.

Extracts ~100-200 canonical templates from millions of raw log lines using
Drain3's fixed-depth parse tree algorithm. Tracks per-template frequency
and flags windows where known-critical patterns appear.

Critical pattern detection (any occurrence = warning alert):
  - "DB semaphore timeout"       → pool exhaustion active
  - "DB pool near exhaustion"    → approaching 15/15 limit
  - "StreamingPersister"         → flush pipeline failures
  - "circuit breaker"            → CLOB API circuit tripped
  - "FAILED"                     → bot state machine failure
  - "kill switch"                → emergency stop engaged

Window anomaly detection (every 60s):
  Updates a per-template exponential moving average baseline.
  Flags templates whose current count > 3× baseline (spike detection).
"""
import os
import time
from typing import Dict, Any, List, Optional, Tuple
from pathlib import Path
from structlog import get_logger

try:
    from drain3 import TemplateMiner
    from drain3.template_miner_config import TemplateMinerConfig
    DRAIN3_AVAILABLE = True
except ImportError:
    DRAIN3_AVAILABLE = False

logger = get_logger()


class LogTemplateMiner:
    """
    Incremental log miner that tails paper_trading.log and extracts patterns.

    Usage::

        miner = LogTemplateMiner()

        # In scheduler loop every 30s:
        alerts = miner.tail_log()
        for alert in alerts:
            logger.warning("Critical log pattern", **alert)

        summary = miner.get_window_summary()
    """

    DEFAULT_LOG_PATH = Path("data/paper_trading.log")

    # Critical patterns → any occurrence triggers a WARNING log
    CRITICAL_PATTERNS: List[str] = [
        "DB semaphore timeout",
        "DB pool near exhaustion",
        "pool near exhaustion",
        "StreamingPersister bulk_insert",
        "kill switch",
        "bot state machine failed",
        "reap_stale_reservations failed",
        "ingest_everything timed out",
    ]

    def __init__(
        self,
        log_path: Optional[Path] = None,
        window_size_seconds: float = 60.0,
        spike_factor: float = 3.0,
    ):
        self.log_path = log_path or self.DEFAULT_LOG_PATH
        self.window_size_seconds = window_size_seconds
        self.spike_factor = spike_factor          # Count > spike_factor × baseline → spike alert

        self._miner: Optional[Any] = None
        self._template_counts: Dict[str, int] = {}    # template_id → count this window
        self._baseline_counts: Dict[str, float] = {}  # template_id → EMA baseline
        self._window_start = time.monotonic()
        # Start at EOF so we only process NEW log lines added after this process started.
        # Starting at 0 replays the entire log history on every restart — the old "FAILED"
        # pattern warnings generated by this very class create a ~10k/min spam feedback loop.
        self._file_pos = int(os.path.getsize(self.log_path)) if self.log_path.exists() else 0
        self._lines_processed = 0
        self._patterns_found: Dict[str, int] = {}     # pattern → total lifetime count

        if DRAIN3_AVAILABLE:
            config = TemplateMinerConfig()
            config.drain_depth = 4
            config.drain_sim_th = 0.5
            config.drain_max_children = 100
            config.profiling_enabled = False
            # In-memory only: no persistence file (avoids file locking issues)
            self._miner = TemplateMiner(config=config)
            logger.debug("LogTemplateMiner initialized (Drain3 in-memory)")
        else:
            logger.warning("drain3 not installed — LogTemplateMiner running in fallback (keyword scan only) mode")

    # ── Core processing ───────────────────────────────────────────────────────

    def process_line(self, line: str) -> Optional[str]:
        """
        Process one log line through Drain3 template miner.

        Returns the matched template string, or None.
        """
        line = line.strip()
        if not line:
            return None

        self._lines_processed += 1

        if not DRAIN3_AVAILABLE or self._miner is None:
            return None  # Fallback: handled by keyword scan in tail_log()

        try:
            result = self._miner.add_log_message(line)
            if result and result.get("cluster"):
                cluster = result["cluster"]
                template_id = str(cluster.cluster_id)
                self._template_counts[template_id] = (
                    self._template_counts.get(template_id, 0) + 1
                )
                return cluster.get_template()
        except Exception:
            pass
        return None

    def tail_log(self) -> List[Dict[str, Any]]:
        """
        Read new lines from paper_trading.log since last call.

        Returns list of dicts for any critical-pattern matches found.
        Each dict has: template, raw_line, pattern, is_critical.
        """
        if not self.log_path.exists():
            return []

        alerts: List[Dict[str, Any]] = []
        try:
            with open(self.log_path, "r", encoding="utf-8", errors="replace") as f:
                f.seek(self._file_pos)
                new_lines = f.readlines()
                self._file_pos = f.tell()

            # Reset file position if log was rotated (file is smaller than our saved pos)
            if self._file_pos > os.path.getsize(self.log_path) + 1:
                self._file_pos = 0

            for line in new_lines:
                template = self.process_line(line)

                # Check critical patterns (works with or without Drain3)
                line_lower = line.lower()
                # Skip our own output to prevent self-referential feedback loops:
                # Any LogMiner warning/log line that contains pattern strings (e.g.
                # "circuit breaker", "FAILED") would re-trigger on the next scan cycle.
                # Skipping all lines that originate from LogMiner itself eliminates
                # the cascade regardless of which pattern triggered it.
                if "logminer:" in line_lower:
                    continue
                for pat in self.CRITICAL_PATTERNS:
                    if pat.lower() in line_lower:
                        self._patterns_found[pat] = self._patterns_found.get(pat, 0) + 1
                        alerts.append({
                            "template": template or line.strip()[:100],
                            "raw_line": line.strip()[:300],
                            "pattern": pat,
                            "is_critical": True,
                            "occurrence_count": self._patterns_found[pat],
                        })
                        break  # Only report first matching pattern per line

        except Exception as e:
            logger.debug("LogTemplateMiner tail_log error: %s", e)

        return alerts

    def get_spike_alerts(self) -> List[Dict[str, Any]]:
        """
        Return templates whose current window count > spike_factor × baseline.
        Indicates a sudden increase in a previously-stable log pattern.
        """
        now = time.monotonic()
        elapsed = now - self._window_start
        if elapsed < 10.0:
            return []  # Too early in window to detect spikes

        spikes = []
        for tid, count in self._template_counts.items():
            baseline = self._baseline_counts.get(tid, 0.0)
            if baseline > 0 and count > self.spike_factor * baseline:
                spikes.append({
                    "template_id": tid,
                    "current_count": count,
                    "baseline": round(baseline, 2),
                    "ratio": round(count / baseline, 2),
                })
        return spikes

    def get_window_summary(self) -> Dict[str, Any]:
        """
        Snapshot of current window. Rotates window if window_size_seconds elapsed.
        Updates EMA baselines at window boundary.
        """
        now = time.monotonic()
        elapsed = now - self._window_start

        if elapsed >= self.window_size_seconds:
            # Update baselines (EMA α=0.3)
            all_templates = set(self._template_counts) | set(self._baseline_counts)
            for tid in all_templates:
                count = self._template_counts.get(tid, 0)
                prev = self._baseline_counts.get(tid, float(count))
                self._baseline_counts[tid] = 0.7 * prev + 0.3 * count
            self._template_counts.clear()
            self._window_start = now
            elapsed = 0.0

        # Top templates by frequency
        top = sorted(self._template_counts.items(), key=lambda x: -x[1])[:10]

        return {
            "drain3_available": DRAIN3_AVAILABLE,
            "window_elapsed_s": round(elapsed, 1),
            "window_size_s": self.window_size_seconds,
            "unique_templates_this_window": len(self._template_counts),
            "total_lines_processed": self._lines_processed,
            "top_templates": [{"id": tid, "count": cnt} for tid, cnt in top],
            "critical_pattern_counts": dict(self._patterns_found),
            "file_pos_bytes": self._file_pos,
        }

    def reset_file_position(self) -> None:
        """Reset log tail to beginning of file (useful after log rotation)."""
        self._file_pos = 0
        logger.debug("LogTemplateMiner: file position reset to 0")
